backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: event
    label: Event
    folder: data/events/
    extension: yml
    format: yml
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Event date, name: event_date, widget: datetime, timeFormat: false}
      - {label: Event time, name: event_time, widget: string}
      - {label: Location, name: location, widget: string}
      - {label: Body, name: body, widget: markdown}
      - {label: Contact name, name: contact_name, widget: string, required: false}
      - {label: Contact e-mail, name: contact_email, widget: string, required: false}
      - {label: Contact phone, name: contact_phone, widget: string, required: false}
      - {label: Link title, name: link_title, widget: string, required: false}
      - {label: Link URL, name: url, widget: string, required: false}

  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Story
            name: story
            widget: markdown

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
      - file: data/settings/units.yml
        label: Units
        name: units
        fields:
          - label: Currency
            name: currency
            widget: select
            options: ['€', '$', '£']
            default: '$'

          - label: Weight
            name: weight
            widget: select
            options: ['kg', ' st', ' lb']
            default: 'lb'
