name: 'Netlify Deploy'

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
