name: 'Netlify Deploy'

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: build/
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
